config/routes.rb
Rails.application.routes.draw do
  resources :table_dogs
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/table_dog.rb
class TableDog < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/table_dogs_controller.rb
class TableDogsController < ApplicationController
  before_action :set_table_dog, only: %i[ show edit update destroy ]

  # GET /table_dogs or /table_dogs.json
  def index
    @table_dogs = TableDog.order(:id_dog).page(params[:page])
  end

  # GET /table_dogs/1 or /table_dogs/1.json
  def show
  end

  # GET /table_dogs/new
  def new
    @table_dog = TableDog.new
  end

  # GET /table_dogs/1/edit
  def edit
  end

  # POST /table_dogs or /table_dogs.json
  def create
    @table_dog = TableDog.new(table_dog_params)

    respond_to do |format|
      if @table_dog.save
        format.html { redirect_to table_dog_url(@table_dog), notice: "Table dog was successfully created." }
        format.json { render :show, status: :created, location: @table_dog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @table_dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /table_dogs/1 or /table_dogs/1.json
  def update
    respond_to do |format|
      if @table_dog.update(table_dog_params)
        format.html { redirect_to table_dog_url(@table_dog), notice: "Table dog was successfully updated." }
        format.json { render :show, status: :ok, location: @table_dog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @table_dog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /table_dogs/1 or /table_dogs/1.json
  def destroy
    @table_dog.destroy

    respond_to do |format|
      format.html { redirect_to table_dogs_url, notice: "Table dog was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_table_dog
      @table_dog = TableDog.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def table_dog_params
      params.require(:table_dog).permit(:id_dog, :nombre, :raza, :peso, :fecha_nac, :vacunas)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/table_dogs_helper.rb
module TableDogsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Desarrollohito2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css">
  </head>

  <body>
  <div class="container"  border: 20% solid darkblue>
    <%= yield %>
    </div>
  </body>
</html>

app/views/table_dogs/_form.html.erb
<%= form_with(model: table_dog) do |form| %>
  <% if table_dog.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(table_dog.errors.count, "error") %> prohibited this table_dog from being saved:</h2>

      <ul>
        <% table_dog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id_dog, style: "display: inline" %>
    <%= form.number_field :id_dog %>
  </div>

  <div>
    <%= form.label :nombre, style: "display: inline" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :raza, style: "display: inline" %>
    <%= form.text_field :raza %>
  </div>

  <div>
    <%= form.label :peso, style: "display: inline" %>
    <%= form.number_field :peso %>
  </div>

  <div>
    <%= form.label :fecha_nac, style: "display: inline" %>
    <%= form.date_field :fecha_nac %>
  </div>

  <div>
    <%= form.label :vacunas, style: "display: inline" %>
    <%= form.text_field :vacunas %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/table_dogs/_table_dog.html.erb
<div id="<%= dom_id table_dog %>">
  <p>
    <strong>Id dog:</strong>
    <%= table_dog.id_dog %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= table_dog.nombre %>
  </p>

  <p>
    <strong>Raza:</strong>
    <%= table_dog.raza %>
  </p>

  <p>
    <strong>Peso:</strong>
    <%= table_dog.peso %>
  </p>

  <p>
    <strong>Fecha nac:</strong>
    <%= table_dog.fecha_nac %>
  </p>

  <p>
    <strong>Vacunas:</strong>
    <%= table_dog.vacunas %>
  </p>

</div>

app/views/table_dogs/edit.html.erb
<h1>Editing table dog</h1>

<%= render "form", table_dog: @table_dog %>

<br>

<div>
  <%= link_to "Show this table dog", @table_dog %> |
  <%= link_to "Back to table dogs", table_dogs_path %>
</div>

app/views/table_dogs/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Table dogs</h1>
<div id="table_dogs">
  <% @table_dogs.each do |table_dog| %>
    <%= render table_dog %>
    <p>
      <%= link_to "Show this table dog", table_dog %>
    </p>

  <% end %>

</div>
<%= link_to "New table dog", new_table_dog_path %>

app/views/table_dogs/new.html.erb
<h1>New table dog</h1>

<%= render "form", table_dog: @table_dog %>

<br>

<div>
  <%= link_to "Back to table dogs", table_dogs_path %>
</div>

app/views/table_dogs/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @table_dog %>

<div>
  <%= link_to "Edit this table dog", edit_table_dog_path(@table_dog) %> |
  <%= link_to "Back to table dogs", table_dogs_path %>

  <%= button_to "Destroy this table dog", @table_dog, method: :delete %>
</div>